#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "OceanicNext"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "nil"
  statusline_iseparator = "bar"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = false
  enable_statusline_mode = true
  statusline_unicode = true
  guifont = "Monospace Regular"
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = true
  filetree_direction = "left"
  default_indent = 4
  expand_tab = true
  # project management
  # project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  project_rooter_outermost = false
  sidebar_width = 35
  # Enable autocomplete layer [[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"
  # line number 
  relativenumber = false
  show_cursor_error = false
  lint_on_save = false
  # file tree
  filemanager = "nerdtree"
  # enable_filetree_gitstatus = true
  # search tools
  file_searching_tools = ['find', 'find -not -iwholename "*.git*" ']

# add custom_plugins: https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = "incsearch"

[[layers]]
  name = "denite"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#verilog"

[[layers]]
  name = "ctrlspace"

[[layers]]
  name = "checkers"

